### ISSUE TITLE
About entries on codalab

### ISSUE THREAD

**Issue by liudaizong** [simongrest/chexpert-entries#1]
Hi! Thanks for your work. Now I have a problem when I try to run my own code on codalab with following command

cl run valid_image_paths.csv:valid_image_paths.csv CheXpert-v1.0:valid src:src "python src/<path-to-prediction-program> valid_image_paths.csv predictions.csv" -n run-predictions --request-docker-image  anibali/pytorch:cuda-9.0

I don't know how to install pandas on the docker to use it. I found that your submitted code also include pandas, can you give me some suggestions? Thanks!

**Comment by inisis** [comment]
you can use docker image yaphets4desmond/easychexpert

**Comment by liudaizong** [comment]
> you can use docker image yaphets4desmond/easychexpert

I will try it, thank you!

**Comment by gokriznastic** [comment]
@inisis @simongrest can you tell me how to change docker image in current codalab worksheet? I am unable to submit because I cannot `import cv2`.

**Comment by simongrest** [comment]
With your `cl run` command you can use the flag `--request-docker-image <docker-image>`. The docker image needs to be hosted on docker cloud (https://cloud.docker.com/)

**Comment by gokriznastic** [comment]
@simongrest Thank you for replying so quickly. I just figured it out minutes ago.

**Comment by swapnil-saha** [comment]
Did anyone use this docker yaphets4desmond/easychexpert for pytorch implementation? I tried to use it but faced some issues.

**Comment by inisis** [comment]
> Did anyone use this docker yaphets4desmond/easychexpert for pytorch implementation? I tried to use it but faced some issues.

Hi, you can find my dockerfile here https://github.com/inisis/chexpert, you can modify that im your owm way.

**Comment by swapnil-saha** [comment]
> > Did anyone use this docker yaphets4desmond/easychexpert for pytorch implementation? I tried to use it but faced some issues.
> 
> Hi, you can find my dockerfile here https://github.com/inisis/chexpert, you can modify that im your owm way.

thanks for your reply. i am making my own docker which works fine except for the open cv library. can you share how you have installed opnecv library in your own docker ?
Thanks in advance

**Comment by inisis** [comment]
> > > Did anyone use this docker yaphets4desmond/easychexpert for pytorch implementation? I tried to use it but faced some issues.
> > 
> > 
> > Hi, you can find my dockerfile here https://github.com/inisis/chexpert, you can modify that im your owm way.
> 
> thanks for your reply. i am making my own docker which works fine except for the open cv library. can you share how you have installed opnecv library in your own docker ?
> Thanks in advance
You can use this CMD in your dockerfile

RUN pip3.6 install opencv-python==4.0.0.21 # you can change it to your own version
